### ISSUE TITLE
Generated srcset only has round numbers

### ISSUE THREAD

**Issue by wirelessed** [imgix/imgix.js#122]
Hi

I'm trying to set a 120px width image with imgix.js:
`sizes="120px"
ix-params='{
  "w": 120
}'`

However, the generated srcset code only has 
w=100 100w
w=200 200w
w=300 300w

is this normal?

**Comment by jayeb** [comment]
Hmm, it's unclear to me based on this information whether you've uncovered a bug or not. A couple of things first:

- Yes, it's intentional that the generated `srcset` list contains only round numbers. When it runs, imgix.js automatically generates a big list of imgix URLs for your image path at a wide variety of different widths. You can see the list of widths we use in [`src/targetWidths.js`](https://github.com/imgix/imgix.js/blob/master/src/targetWidths.js), but essentially the strategy can be described as "every width from 100 to 5000 in increments of 100, plus a bunch of other numbers representing known popular screen sizes". That list is then [capped](https://github.com/imgix/imgix.js/blob/master/src/targetWidths.js#L136-L138) based on the maximum possible screen size of the device on which imgix.js is running at the moment.

- If you're just trying to set an image to an explicit width as in your example, then imgix.js isn't really the best tool. imgix.js is good for generating a comprehensive `srcset` list, which is important when you don't know what the rendered dimensions of your image is going to be (usually because its size is dependent on the size of the browser window). If you know the exact width at which the image is supposed to be rendered on the page, as you do in your example, then generating your `srcset` is pretty trivial and you really don't need imgix.js's help.

- Finally, what screensize were you testing this on? It's possible we have a bug here--the `srcset` you provided in your example implies that the device was more than 300px wide but less than 320px, which is a strange size indeed.

**Comment by wirelessed** [comment]
Hi. 
Thanks for the clarification. 

I couldn't find any documentation on targetwidths.js hence I asked the question. I was expecting imgix.js to generate the srcset based on the width I specified and not in round numbers e.g. 120px, 240px, etc. 

I was testing in Chrome using the inspect mode at 320px. I didn't paste the full list of widths generated so I don't think there's a bug.

**Comment by jayeb** [comment]
Yea, you're absolutely right that in this case the `srcset`-generation code should probably take the provided `sizes` attribute into account. I'll open a separate ticket for that, but as a fair warning it's probably not going to be a super-high priority fix, given that this use-case isn't really what imgix.js is designed for.

**Comment by jayeb** [comment]
Separate ticket is here: #124. Closing this ticket now.
