### ISSUE TITLE
img tag doesn't work with ix-path in Vue.js app

### ISSUE THREAD

**Issue by mckrava** [imgix/imgix.js#139]
I'm trying to use `imgix.js` library in my Vue.js application. 
```
"vue": "^2.6.10",
"imgix.js": "^3.4.1",
```
I'm initializing it in my `main.js` file before creating Vue app:
```
import 'imgix.js'

window.imgix.config.host = 'my-host.imgix.net';
window.imgix.config.useHttps = true;
window.imgix.init({
  force: true
})
```
and as result I have initialized `imgix` instance with setted host value inside `window` object.
But when I try render `<img>` tag, it doesn't render image:
```
           <img
                :ix-path="`${product.id}/${product.images[0].imgName}`"
                :ix-params='{
                    "w": 300,
                    "h": 500,
                    "fit": "crop",
                    "crop": "right"
                  }'
                alt="Demo test img"
            >
```

result in browser:
```
<img 
   ix-path="aMvl6NfZBimrHj7CebyS/1558953740707_845212893323_livestock-feed-pellet- 
   machine.jpg" 
   ix-params="[object Object]" 
   alt="Demo test img"
>
```

Which step is wrong in my flow?

**Comment by agcty** [comment]
I got the same problem, did you manage to fix it?

**Comment by T0TProduction** [comment]
You need to manually call imgix.init on e.g. mounted()

We did this by setting up a vue plugin for imgix:

```js
import Vue from 'vue';
import { ImgixJs } from 'imgix.js';

declare const window: Window & {
  imgix: ImgixJs;
};

// we need to do this, so that imgix is a globally defined variable
require('imgix.js');

// this is globally defined
window.imgix.config.host = 'your-subdomain.imgix.net';
Vue.prototype.$imgix = window.imgix;
```

You can then use
```js
this.$imgix.init(); 
```
in any vue page. Either in mounted(), or even in other functions when e.g. you update the url you're using

Hope that helped.

**Comment by agcty** [comment]
I actually use imgix-core now:

```javascript
import ImgixClient from "imgix-core-js";
var imgixClient = new ImgixClient({
  domain: process.env.IMGIX_URL || "devURL.imgix.net"
  // Do not use signed URLs with `secureURLToken` on the client side,
  // as this would leak your token to the world. Signed URLs should
  // be generated on the server.
});

// let buildUrl = client.buildUrl();

export { imgixClient };

```

and use it like this in a component



```javascript
import { imgixClient } from "@/plugins/imgix.js";

imgObject = {
          src: imgixClient.buildURL(this.photos[0].path, {
            auto: "format",
            q: 80
          }),
          dataSrcSet: imgixClient.buildSrcSet(this.photos[0].path),
          lqip: imgixClient.buildURL(this.photos[0].path, {
            w: 300,
            q: 20,
            auto: "format"
          })
        };
```

**Comment by sherwinski** [comment]
Thanks for all the input @T0TProduction and @agcty!
Sorry to go on a bit of a tangent here but if imgix were to build/support an official Vue.js plugin, where would be a good place to start? Any particular gotchas or things to look out for? I am not familiar with Vue at all but will have to dive into it eventually if/when we decide to build out something officially. Just looking for input from those who have thought about this already and clearly gotten somewhere with it. Thanks!

PS @agcty really glad to see someone making use of `buildSrcSet` 😁

**Comment by T0TProduction** [comment]
The way i see it, there are two systems vue provides that you could use. Either exclusive, or a combination of both:

**1. Vue plugins** [Docs](https://vuejs.org/v2/guide/plugins.html)

Just like in my MVP-implementation, plugins provide a way for users to include your library with a single line of code. You can inject your library into the Vue prototype, as seen in my example, but you can also hook e.g. the `init` function into the `updated` and `mounted` functions that Vue uses.
Hooking them into those would automate the init.
They would still use the typical `<img>` tag the way imgix is used in raw html.

**2. Vue components** [Docs](https://vuejs.org/v2/guide/components.html)
(in the example they are built programatically, i personally create them as their own .vue file)

Vue components are similar to other web frameworks you might know. They provide ( optionally ) scoped vue code, which includes html, css and js/ts. You could create a component, which users could import and then use instead of using the `<img>` tag. Providing all possible settings to the user via a configuration (can be done in many ways, including opening an API to the user in the Vue prototype, similar to step 1 ), and allowing them to override in every single use of the `<imgix>` component with properties (input variables for the component, eg. the source in `<imgix :source="ourSource"/>`) would allow them to never need to touch the imgix code itself. You could then call `init` inside the `update` function of the component, which removes the need to either call it manually, or hook it into globals.


**My conclusion**
You should definitely think about what you want to achieve with the vue lib before developing it, as e.g. my implementation is pretty much just a nice vue-compatible import, and option 1 only adds a bit more functionality. 
In general, i would probably go for option 2, but depending on flexibility and ease of use you might want to support all of above mentioned.

**Comment by agcty** [comment]
@sherwinski why are you glad I'm using buildSrcSet? 😅 is nobody else using it? I actually think this feature is really really useful! As for a imgix vue-library, I personally would favour using imgix-core-js as you can actually use it with SSR as well and don't have to worry about document or window undefined errors as is the case when using imgix.js. I just created a small code sandbox (https://codesandbox.io/s/vue-imgix-sample-component-e0r1x) that should be enough for you to get an idea of how it could be implemented :) Also I'm happy to do a PR and help out if there's going to be an official repo!

**Comment by T0TProduction** [comment]
Sure, I'd be interested in being kept up to date! ✨

**Comment by agcty** [comment]
@frederickfogerty would also be very interested! 🥳

**Comment by T0TProduction** [comment]
Oh, I just now looked at the example you posted here @agcty 

>  I just created a small code sandbox (https://codesandbox.io/s/vue-imgix-sample-component-e0r1x) that should be enough for you to get an idea of how it could be implemented :) 

This is pretty much exactly what I was going for with my idea of option 2!

After adding all imgix functionalities other libraries already support into that component and potentially abstracting properties a bit, it would be the perfect imgix-vue-module!

I also love how the updating does not need to be hooked into anything (neither local `updated()` or `mounted()`, nor globals of that sort) because you used a computed property which also takes care of the src, etc. -generation. Should perform a lot better than spamming `imgix.init`!
It *should* actually solve an issue I already encountered when using `imgix.init` after dynamically changing source URLs. Sometimes we would need to use `imgix.init({force:true})` to update specific images.
