### ISSUE TITLE
after changing ix-path, imgix.init() does not apply new srcsets

### ISSUE THREAD

**Issue by T0TProduction** [imgix/imgix.js#162]
We're using imgix within nuxt/vue.js
We built a vue plugin ( as shown [here](https://github.com/imgix/imgix.js/issues/139#issuecomment-545878953) ) to have the imgix.init function available everywhere, and call it when mounting. This works, and shows all images as expected.

After having changed the ix-path though, even if we call imgix.init again, the srcset is not being updated. 

One can see this here: 
![image](https://user-images.githubusercontent.com/18548570/67483905-1e2f6e00-f667-11e9-8e8e-22d1d0fd6b71.png)

My assumption is, that imgix is skipping this img tag, as it has already existing srcset.

Is this an error that can be explained, or would you assume there is some other issue on my side.

**Comment by sherwinski** [comment]
Hey @T0TProduction, it looks like this is due to imgix.js being [idempotent](https://github.com/imgix/imgix.js#imgixinit-idempotency). So yes, it is likely that the img tag is being skipped over. For this issue, calling `imgix.init()` while passing in the `force:true` option should fix it.

I do think this can be a bit confusing and could stand to be improved. Some adjustments are needed to ensure that images are reprocessed only based on input changes. I'll make a note to look into it sometime in the future. Pull requests are always welcome as well.
