### ISSUE TITLE
Responsive Background Image

### ISSUE THREAD

**Issue by botrondana** [imgix/imgix.js#188]
Looking for suggestions or work arounds for IMGIX not creating responsive images for background images and serving them to website.

**Comment by daletom** [comment]
Hi @botrondana , the imgix.js library isn't able to create a responsive background image because it doesn't actually know the size of the container.  A work around could be to use the react library (not sure what your site is built on), which actually uses react-measure to measure the size of the container. It works really well for doing responsive background images: https://github.com/imgix/react-imgix#background-mode  

Hope that is helpful in some way!
