### ISSUE TITLE
How to apply imgix-js on command?

### ISSUE THREAD

**Issue by sergiotapia** [imgix/imgix.js#31]
http://stackoverflow.com/questions/30444716/how-to-apply-imgix-js-on-command

---

    $(document).ready(function () {
        var imgixOptions = {
            updateOnResizeDown : true,
            updateOnPinchZoom : true,
            fitImgTagToContainerWidth: true,
            fitImgTagToContainerHeight: true,
            autoInsertCSSBestPractices: true,
            pixelStep : 5
        };

        imgix.onready(function() {
            imgix.fluid(imgixOptions);
        });
    });
     
---

This works as expected on dom ready however some pieces of my site load dynamically using AJAX.

How can I trigger the imgix-js library to load the images the way it does on dom ready?

**Comment by jayeb** [comment]
For this project, we'd generally prefer to use GitHub issues to discuss bugs or feature requests for the library, rather than answer questions about implementation. I'm gonna close this ticket, but I've answered your question on Stack Overflow and would be happy to discuss it further there if my answer isn't sufficient.
