### ISSUE TITLE
An element that is imgix fluid, and has `display:none` initially, does not get the image updated once it is shown

### ISSUE THREAD

**Issue by victorwhy** [imgix/imgix.js#84]
So a little background, we want to be able to hide on element and show another element for a test, but using a display: none on the original element, prevents the imgix.js from applying the fluid image for that element.  As a result, when that element is shown, it doesn't have the actual image attached.

Resizing the window forces the call to get the image, but I don't see any documentation to force a "refresh", or anything to have it show after being `display: none`.  Our current workaround is to have it be height 0 and visibility hidden, but that seems like a bad hack.

Any input on this would be great!  Here's a gif to illustrate:

![image](http://g.recordit.co/hib8dx6omZ.gif)

**Comment by jayeb** [comment]
Yup, you're right. The way `imgix.fluid()` is set up right now, it needs to measure an image's container in order to request the properly-sized image, and a hidden container just can't be measured correctly.

The solution here is to force a manual refresh by calling `.reload()` on the `imgix.FluidSet` object you get from the original `imgix.fluid()` call. For example:

```js
// cache the return of imgix.fluid()
var fluidSet = imgix.fluid();

function onUnhideOrWhatever() {
  // call .reload manually
  fluidSet.reload();
};
```

I'm gonna close this ticket (we like to keep GitHub issues focused on bug reports and feature requests), but if you've got any other questions I'm happy to answer them through our support channel. Just shoot an email to support@imgix.com and I'll scoop it up as it comes in.

**Comment by victorwhy** [comment]
@jayeb ah okay, it would be great to listen in on that event for it to fire a reload on an element with the fluid class, but I can use this to work around.  Thanks!
