### ISSUE TITLE
Images in fixed position are not detected

### ISSUE THREAD

**Issue by haithamalkhatib** [imgix/imgix.js#86]
Noticed that images that are in fixed position or when their parents are in fixed position imgix does not pick up the image.

Tried with data-src attribute where the element itself was in fixed position and was given a height.

Another situation is when the parent was in fixed position and the element was a img with a position of relative. 

In both cases the imgix.js would not detect the images.

**Comment by jayeb** [comment]
Can you give me a Codepen example of this behavior?

My instinct tells me this is an issue with the sizing of the parent element--when you call `imgix.fluid()`, the *parent* of the image element is what determines the size of the image being requested, rather than the image itself. Therefore, if you're placing your image element in a parent container that doesn't have at least one dimension specified, the image element is going to assume its size is `0` and an image won't be requested.

**Comment by jayeb** [comment]
Closing this issue, since it's no longer relevant since the release of imgix.js 3.0.0.
