### ISSUE TITLE
fluid img tag uses height of parent instead of it´s own height

### ISSUE THREAD

**Issue by kschu91** [imgix/imgix.js#88]
were using imgix fluid with default settings and the following overwritten settings:
`imgix.fluid({
            "fluidClass": "responsive-image",
            "lazyLoad": true
        });`

Fluid uses the height of the parent container of an image tag to calculate the width/height of itself.
In my opinion this is a wrong behavior. In our case this causes the image to be extremly large since the parent container is much more bigger than the image tag itself.

Have a look at src/fluid.js on line 152 the parent element is used if the current element is an image tag.
`elemSize = imgix.helpers.calculateElementSize(imgix.isImageElement(elem) ? elem.parentNode : elem),`

If I negotiate this condition everything is working well with the width/height detection.
`elemSize = imgix.helpers.calculateElementSize(!imgix.isImageElement(elem) ? elem.parentNode : elem),`

**Comment by jayeb** [comment]
Thanks for the report, Kevin. The behavior you're noting as a bug is actually the intended behavior, for a number of reasons--I've provided a more thorough explanation below, but to solve your immediate problem I recommend simply wrapping your `<img>` tag in a container element of some kind and applying your sizing code to the wrapper tag instead.

As for the question of *why* we've chosen to implement the library in this way, you've already rightly pointed out that we have two options here:

1. Build the "fluid" imgix URL based on the size of the `<img>` tag's immediate parent (the current behavior of imgix.js)
2. Build the "fluid" imgix URL based on the explicit size of the `<img>` tag (the suggested behavior)

In the most basic case, these two options will result in the exact same behavior. If you want an image to be half the width of the page, you set the measurable element (the parent in scenario 1 or the `<img>` itself in scenario 2) to `width: 50%` and everything behaves as expected.

But the devil is in the details, as they say, and the corner-cases for image-sizing behavior all point to scenario #1 being the better solution. Consider some of the following scenarios:

- The default case, where you haven't applied any size-specific CSS to your `<img/>` tag, will result in no image at all being downloaded (since the image has a default size of 0×0, as far as the browser is concerned). This violates the base expectation of someone trying out imgix.js for the first time: "Okay, I put the correct class on my image and declared `imgix.fluid()` correctly, so why hasn't my image shown up at all?"
- Since the browser applies secondary resizing to images based on the specified dimensions of the `<img>` tag, applying such dimensions to the tag itself can actually "overwrite" explicitly declared imgix parameters, such as [`fit=min`](https://docs.imgix.com/apis/url/size/fit).
- What if you wanted your image to be the same height as a sibling element? There's no easy way to declare this with CSS, but if the image is sized based on its parent element (which is, in turn, sized by its children), this becomes possible.

In a future version of imgix.js we'll likely make this behavior more customizable, but at the moment it's going to stay as it is. Hopefully this was helpful!
