### ISSUE TITLE
onLoad callback timing

### ISSUE THREAD

**Issue by jordanthomas** [imgix/imgix.js#92]
In Safari I'm seeing some weird behavior where `fluid` is creating two requests to Imgix for each image. One for the "preload" and one when the target element `src` is updated. It doesn't always happen, it appears tied to caching in some capacity.

The callback is fired once the "preload" image onload occurs, but in the scenario I'm describing the image isn't actually done loading at this point.

Boiling it down – the onload callback fires too early in some cases in Safari.

Here's a fiddle that should demonstrate the Safari behavior:
https://jsfiddle.net/6vtr8bjg/

**Comment by rikh42** [comment]
I am also seeing issues with onload not firing at all. Occasionally fluid images are not replaced. I've had to give up on imgix.js because of this, and in building my own replacement figured out it is probably related to the onload event.

I also see consistent issues with imgix.js on mobile safari that I also think are related to caching and onload events mis-firing. eg, open safari, visit site, switch away from safari and do something else for a bit, switch back to safari such that it re-renders the page - image loading goes wrong at this point.

Hope this helps.

**Comment by paulstraw** [comment]
@jordanthomas: This is merged and released in `2.2.3`!

@rikh42: [We're working on imgix.js 3.0](https://github.com/imgix/imgix.js/issues/98), which will be released soon and should mitigate these issues. 😄

**Comment by jordanthomas** [comment]
👍🏻
