### ISSUE TITLE
Images don't appear on initial load

### ISSUE THREAD

**Issue by jbschrades** [imgix/imgix.js#97]
I'm seeing an issue where imgix-fluid images sometimes don't appear when a page is loaded.  I thought this might be an issue with my implementation, but I experienced the same thing on both imgix examples:

https://www.imgix.com/js-examples/imgix-img.html
https://www.imgix.com/js-examples/imgix-bg.html

If I resize the screen, then the images load.  Behavior is not consistent - sometimes the images load, sometimes not.  Using Chrome 50.0.

**Comment by toobulkeh** [comment]
When it doesn't load, there is no src set on the image from the data-src tag. I HTH.

**Comment by paulstraw** [comment]
Hey folks. This was a regression in Chrome 50. It has been resolved as of 50.0.2661.94. We're also currently working on a new major release of imgix.js that will help avoid issues like this in the future.

**Comment by jbschrades** [comment]
Indeed. Thanks for the quick response!

**Comment by pushred** [comment]
@paulstraw do you have any recommendations for a workaround in the interim? Would using client hints help? Unfortunately in my case there is no fallback strategy for fluid images since they are background images, yet they are pretty important as it's e-commerce. 

For reference could you also link the related Chromium issue(s)? I scanned the changelogs since .75 but couldn't find anything that seemed to correlate with this behavior.

**Comment by jbschrades** [comment]
I think it's https://bugs.chromium.org/p/chromium/issues/detail?id=605346
